# Tiles storage
v2:
  public: true
  formats: [pbf]
  uri: cassandra://
  params:
    maxzoom: 15 # Note: this max zoom is inclusive
    keyspace: v2
    cp: {var: cassandra-servers}
    username: {var: cassandra-user}
    password: {var: cassandra-pswd}
    repfactor: 4
    durablewrite: 0
    createIfMissing: true

oz:
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: v2}

# Final raster source
osm-intl:  # This name is the default Kartotherian leaflet test app layer name
  public: true
  formats: [png,json,headers,svg,jpeg]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
  uri: vector://
  xml:
    npmpath: ["@mapbox/mapbox-studio-osm-bright", "project.xml"]
    # loader: "@kartotherian/osm-bright-style"  
  xmlSetParams:
    source: {ref: oz}

v2-lite:
  public: true
  formats: [pbf]
  uri: cassandra://
  params:
    maxzoom: 14 # Note: this max zoom is inclusive
    keyspace: v2lite
    cp: {var: cassandra-servers}
    username: {var: cassandra-user}
    password: {var: cassandra-pswd}
    repfactor: 4
    durablewrite: 0
    createIfMissing: true

oz-lite:
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: v2-lite}
