# Generates vtiles from database
 
### gen lite tiles for mobile
gen-lite:
  public: true
  formats: [pbf]
  uri: bridge://
  xml: "/etc/tilerator/data_tm2source_lite.xml"
  xmlSetDataSource:
    if:
      dbname: gis
      host: 'localhost'
      type: postgis
    set:
      host: {var: osmdb-host}
      user: {var: osmdb-user}
      password: {var: osmdb-pswd}

ozgen-lite:
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: gen-lite}

v2-lite:
  public: true
  formats: [pbf]
  uri: cassandra://
  params:
    maxzoom: 15
    keyspace: v2lite
    cp: {var: cassandra-servers}
    username: {var: cassandra-user}
    password: {var: cassandra-pswd}
    repfactor: 4
    durablewrite: 0
    createIfMissing: true

oz-lite:
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: v2-lite}


### Basemap without POIs
gen_basemap:
  public: true
  formats: [pbf]
  uri: bridge://
  xml: "/etc/tilerator/data_tm2source_base.xml"
  xmlSetDataSource:
    if:
      dbname: gis
      host: 'localhost'
      type: postgis
    set:
      host: {var: osmdb-host}
      user: {var: osmdb-user}
      password: {var: osmdb-pswd}

basemap:
  public: true
  formats: [pbf]
  uri: cassandra://
  params:
    maxzoom: 15
    keyspace: basemap
    cp: {var: cassandra-servers}
    username: {var: cassandra-user}
    password: {var: cassandra-pswd}
    repfactor: 4
    durablewrite: 0
    createIfMissing: true

substbasemap:  # only for basemap
  public: true
  formats: [pbf]
  uri: substantial://
  params:
    source: {ref: gen_basemap}
    minzoom: 10
    maxsize: 100
    layers: [water, landuse, landcover]

ozbasemap: # faut tester 
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: basemap}


# Generate POIs layer
gen_poi:
  public: true
  formats: [pbf]
  uri: bridge://
  xml: "/etc/tilerator/data_tm2source_poi.xml"
  xmlSetDataSource:
    if:
      dbname: gis
      host: 'localhost'
      type: postgis
    set:
      host: {var: osmdb-host}
      user: {var: osmdb-user}
      password: {var: osmdb-pswd}

poi:
  public: true
  formats: [pbf]
  uri: cassandra://
  params:
    maxzoom: 15
    minzoom: 10
    keyspace: poi
    cp: {var: cassandra-servers}
    username: {var: cassandra-user}
    password: {var: cassandra-pswd}
    repfactor: 4
    durablewrite: 0
    createIfMissing: true

ozpoi:
  public: true
  formats: [pbf]
  uri: overzoom://
  params:
    source: {ref: poi}

